/* 
Code generated by Fahmin GULIYEV

Write a program made of 2 processes: the parent reads data from the standard
input and transmit them to its child through a pipe, the child then prints them on
the standard output. The parent then waits for the termination of the child
process.
void copy(int fdsrc, int fddst) 

./a.out < /bin/ls > toto
cmp /bin/ls toto

*/
#include <stdio.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdlib.h>
#include <wait.h>
#include <string.h>
#include<sys/types.h>
#include<fcntl.h>



void copy(int fdsrc, int fddst){
    char c;
    for (; read(fdsrc, &c, 1) > 0;){
        write(fddst, &c, 1);
    }
}




void main(int argc, char const *argv[]){
    int tube[2];
    if (pipe(tube) != 0){
        perror("Pipe Error");
        exit(1);
    }

    int pid = fork();
    if (pid == -1){
        perror("Fork failed");
        exit(2);
    }
    else if (pid == 0){
        close(tube[1]);
        copy(tube[0], 1);
        exit(3);
    }
    else{
        close(tube[0]);
        copy(0, tube[1]);
        close(tube[1]);
    }
}